config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/thankyou', to: 'pages#thankyou'

  resources :users, only: [:update]

  resources :skills, only: %i[index create edit update]

  resources :organisations, except: %i[destroy] do
    resources :donations, only: %i[create]
    resources :posts, only: %i[index show new create edit update]
    resources :needs, only: %i[index create edit update]
  end

  resources :donations, only: %i[show]

  get '/profile', to: 'profiles#show'

  resources :chatrooms, only: :show

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # skip_before_action :authenticate_user!, except: :new
  before_action :set_profile, only: %i[show create edit update]

  def show
    @profile = current_user
    @skill = Skill.new
    @skills = Skill.where(user: @profile)
    @organisation = current_user.organisation
  end


  # def create
  #   @profile = Profile.new(profile_params)
  #   @profile.user = current_user

  #   if @profile.save
  #     redirect_to profile_path(@profile), notice: "Update ok"
  #   else
  #     render :new, status: :unprocessable_entity
  #   end
  # end

  # def edit
  #   # @profile = Profile.update(current_user)
  #   # @profile.user = current_user
  # end

  # def update
  #   @profile.update(current_user)
  #   redirect_to profile_path
  # end

  private

  def set_profile
    # @profile = Profile.find(params[:id])
    @profile = current_user
  end

  # def profile_params
  #   params.require(:profile).permit(:description, :first_name, :last_name)
  # end

end

app/views/profiles/show.html.erb
<div class="profile-background">
  <div class="container mx-auto">
    <div class="d-flex justify-content-center">
      <div class="my-4 mt-5">
          <% if @organisation.nil? %>
            <%= link_to 'Create organisation ', new_organisation_path(@organisation), class:"button" %>
          <% else %>
            <%= link_to "Edit organisation", edit_organisation_path(@organisation),  class:"button" %>
          <% end %>
      </div>
    </div>
    <div class="d-flex justify-content-between p-5">
      <div class ="profile_box p-4">
        <div class="container mt-4" style="text-align: center">
          <h2>My Profile</h2>
          <% if current_user.photo.attached? %>
            <%#= cl_image_tag(current_user.photo.key, :width => 200, :crop => "pad", :radius => "max")%>
            <i class="pro_img"><%= cl_image_tag(current_user.photo.key)%></i>
          <% end %>

          <ul class="list-unstyled">
            <li class="p-2"><i class="fa-regular fa-envelope"></i> <%=  current_user.email %></li>
            <li class="p-2"><strong>Name: </strong><%=  current_user.first_name %> <%=  current_user.last_name %></li>
            <li class="p-2"><strong>Description: </strong><%=  current_user.description %></li>
          </ul>
          <%= link_to 'Edit', edit_user_registration_path, class: 'button' %>
            <div class="pt-5 mt-3"><%= image_tag 'strong.png', width: 50, height:50 %> <h3>Add your skills</h3>
            </div>
            <div class="accordion" id="accordionExample">
              <div class="accordion-item">
                <%# <h2 class="accordion-header" id="headingOne"> %>
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                    <h6>Skills I would like to offer</h6>
                  </button>
                <%# </h2> %>
                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                  <div class="accordion-body">

                    <%= render "skills/form", skill: @skill, organisation: @organisation %>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>

      <div class="flex-grow-1 ps-3">
        <div class="skillset_box p-4" style="text-align: center">
          <div class="container m-2">
            <p class="p-2 m-3"><%= image_tag 'skills.png', width: 40, height:40 %><h3>Your skills</h3></p>
            <ul class="list-group">
              <% @skills.each do |skill| %>
                <li class="list-group-item"> <%= image_tag Skill::SKILLS_AND_ICONS[skill.name] %> <strong><%= skill.name %></strong></li>
                <li class="list-group-item"><%= skill.description%></li>
                <br>
              <% end %>
            </ul>
          </div>
        </div>

        <div class="donations_box mt-4 p-4" style="text-align: center">
          <div class="container m-2">
            <p> <%= image_tag 'donate small.png', width: 40, height:40 %><h3>Your donations</h3></p>
              <ul class="list-group pb-6 pt-1">
                <% @profile.donations.each do |donation| %>
                  <li class="list-group-item"><strong><%= donation.organisation.name%></strong> <i class="fa-solid fa-hand-holding-dollar"></i></li>
                  <li class="list-group-item"><%= donation.quantity%><%= donation.type_of_donation%> - <%= donation.description%></li>
                  <br>
                <% end %>
              </ul>
          </div>
        </div>

        <% unless @organisation.nil?  %>
          <div class="donations_box mt-4 p-4" style="text-align: center">
            <div class="container m-2">
            <%= image_tag 'donations received small.png', width: 50, height:50 %><h2>Donations you have received</h2>
              <ul class="list-group pb-6 pt-1">
                <% @organisation&.donations&.each do |donation| %>
                    <li class="list-group-item"> The user <strong><%= donation.user.email %></strong> donated to  <strong><%= donation.organisation.name %></strong></li>
                    <li class="list-group-item">Amount: <strong><%= donation.quantity%></strong></li>
                    <br>
                <% end %>
              </ul>
            </div>
          </div>
      <% end %>
      </div>
    </div>
  </div>
</div>