config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/thankyou', to: 'pages#thankyou'

  resources :users, only: [:update]

  resources :skills, only: %i[index create edit update]

  resources :organisations, except: %i[destroy] do
    resources :donations, only: %i[create]
    resources :posts, only: %i[index show new create edit update]
    resources :needs, only: %i[index create edit update]
  end

  resources :donations, only: %i[show]

  get '/profile', to: 'profiles#show'

  resources :chatrooms, only: :show

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  belongs_to :user
  has_many :posts
  has_many :donations, dependent: :destroy
  has_one_attached :photo
  has_many :needs

  accepts_nested_attributes_for :needs, reject_if: :all_blank, allow_destroy: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name ],
      associated_against: {
      needs: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  skip_before_action :authenticate_user!, except: :new

  def index
    if params[:query].present?
      # @organisations = Organisation.where("name ILIKE ?", "%#{params[:query]}%")
      @organisations = Organisation.global_search(params[:query])
    else
      @organisations = Organisation.all
    end

    @markers = @organisations.geocoded.map do |organisation|
      {
        lat: organisation.latitude,
        lng: organisation.longitude,
        info_window: render_to_string(partial: "info_window", locals: {organisation: organisation}),
        # image_url: helpers.asset_url("location-dot-solid.png")
      }
    end
  end


  def show
    @organisation = Organisation.find(params[:id])
    @donation = Donation.new
    @need = Need.new
    @needs = @organisation.needs
    @post = Post.new
    @post = @organisation.posts
  end

  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.new(organisation_params)
    @organisation.user = current_user

    if @organisation.save
      redirect_to organisations_path(@organisation), notice: "New organisation created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    set_organisation
  end

  def update
    set_organisation
    @organisation.update(organisation_params)
    redirect_to organisation_path
  end

  private

  def set_organisation
    @organisation = Organisation.find(params[:id])
  end

  def organisation_params
    params.require(:organisation).permit(:name, :address, :description, :photo, :website, :email, needs_attributes: [:id, :_destroy, :description, :name])
  end
end

app/views/organisations/_form.html.erb
<%= simple_form_for organisation, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |f| %>

  <%= f.input :photo, as: :file %>
  <%= f.input :name, as: :text, placeholder: "Add the name of your Organisation" %>
  <%= f.input :address, as: :text, placeholder: "Where is your organisation located? enter the address" %>
  <%= f.input :description, as: :text, placeholder: "Tell us a bit about the causes and the goals of your organisation" %>
  <%= f.input :website, as: :text,  placeholder: "How can people find you and read more about you? Enter your website" %>
  <%= f.input :email, as: :text, placeholder: "Enter email so people who are interested in your organisation can reach out to you"%>
  <template data-nested-form-target="template">
    <%= f.simple_fields_for :needs, Need.new, child_index: 'NEW_RECORD' do |need_fields| %>
      <%= render "need-form", f: need_fields %>
    <% end %>
  </template>

  <%= f.simple_fields_for :needs do |need_fields| %>
    <%= render "need-form", f: need_fields %>
  <% end %>

  <!-- Inserted elements will be injected before that target. -->
  <div data-nested-form-target="target"></div>

  <button type="button" data-action="nested-form#add" class="button">Add a skill</button>
  <%= f.submit "Submit", class:'button' %>
<% end %>

<div class="my-5">
<%= link_to 'Back', profile_path, class:"button" %>
</div>

app/views/organisations/_info_window.html.erb
<%= link_to organisation_path(organisation) do %>
  <%= cl_image_tag(organisation.photo.key,
        width: 200, height: 150, crop: :fill, class:'rounded-3 pb-2') %>
<% end %>
  <h6 p-3><%= organisation.name %></h6>
  <p><%= organisation.address %></p>

app/views/organisations/_need-form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <%= f.input :name, collection: Need::NEEDS_AND_ICONS.keys, label: 'Skill Needed'  %>
          <%= f.input :description, as: :text, placeholder: "Give details concerning the needed skill." %>
  <button type="button" data-action="nested-form#remove" class="button my-3">Remove Skill</button>

  <%= f.hidden_field :_destroy %>
</div>

app/views/organisations/edit.html.erb
<div class="container p-20 mt-5">
        <h2>Edit your Organisation</h2>
        <%= render "form", organisation: @organisation %>

</div>

app/views/organisations/index.html.erb
<div class="background">
  <div class="banner" style="background-image: url(https://images.unsplash.com/photo-1564750576234-75de3cc54053?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2938&q=80)">
    <h2>Organisations</h2>

      <div class="search">
        <%= form_with url: organisations_path, method: :get, class: "d-flex  w-50  mx-auto" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control opacity-75",
          placeholder: "Search by organisation name or skills"
        %>
      <button <%= submit_tag "Search", class: "searchButton"%>
        <i class="fa fa-search"></i>
      </button>
      <% end %>
      </div>
    <br>
    <br>
    <a href="#map" class="button-light p-3">View Map</a>
  </div>


  <div class="container p-5">
    <div class="row">
      <% @organisations.each do |organisation|%>
        <div class="col-4">
          <%= link_to organisation_path(organisation) do %>
            <div class="card-organisation mb-5 mx-2">
              <% if organisation.photo.attached? %>
                <%= cl_image_tag(organisation.photo.key, :crop => "pad", :class => "card-organisation-img") %>
              <% end %>
              <div class="card-organisation-block">
                <h5><%= organisation.name %></h5>
                <h6><i class="fa-solid fa-location-dot p-1"></i><%= organisation.address %></h6>
                <p><%= organisation.description.truncate(150)%></p>
                <h6><strong>Website: </strong><%= organisation.website %></h6>
                <h6><strong>E-mail: </strong><%= organisation.email %></h6>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div id="map" class="container" style="width: 100%; height: 700px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/organisations/new.html.erb
<div class="container p-20 my-5">
        <h3>Create a new organisation</h3>
        <%= render "form", organisation: @organisation %>

</div>

app/views/organisations/show.html.erb
<% content_for :meta_title, "#{@organisation.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @organisation.description %>
<% content_for :meta_image, cl_image_path(@organisation.photo.key) %>

<div class="container org-show">
  <div class="row">
    <div class=" col-12 col-lg-8">
      <div class="d-flex justify-content-start my-5">
        <% if @organisation.photo.attached? %>
            <%= cl_image_tag(@organisation.photo.key, :width=> 670, :crop=>"pad", :radius=>10) %>
        <% end %>
      </div>
      <h3><%= @organisation&.name %></h3>
      <h5><i class="fa-solid fa-location-dot p-1"></i><%= @organisation&.address %></h5>
      <p><%= @organisation&.description %></p>
      <h5><%= @organisation&.email %> </h5>
      <a href="<%= @organisation&.website %>">Visit our official website</a>

      <% if @organisation == current_user&.organisation %>
        <div class="container p-5">
          <%= link_to "Create a new post!", new_organisation_post_path(@organisation), class: "button" %>
        </div>

        <div class="container p-5">
          <h3>Specify the needs of your organisation here:</h3>
          <%= render "needs/form", need: @need, organisation: @organisation %>
        </div>
       <% end %>


      <%# <%= link_to "create a post", new_organisation_post_path %>
      <div class="my-5">
        <h3>Skills Needed for our Organisation</h3>
        <div class="accordion" id="accordionExample">
          <% @needs.each_with_index do |need, index| %>
            <div class="accordion-item">
              <h2 class="accordion-header pb-2" id="heading<%= index %>">
                <button class="accordion-button ab-skills collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= index %>" aria-expanded="true" aria-controls="collapse<%= index %>">
                  <%= need.name %>
                </button>
              </h2>
                <div id="collapse<%= index %>" class="accordion-collapse collapse" aria-labelledby="heading<%= index %>" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    <%= need.description%>
                    <div class="mt-4 mb-2">
                      <a href="mailto:<%= @organisation.email %>?subject=I%20would%20like%20to%20volunteer&body=Hello%20<%= @organisation.name %>%0D%0A%0D%0AI%20am%20reaching%20out%20to%20you%20to%20offer%20my%20skills%20and%20help%20you%20out%20on%20your%20cause.%0D%0AHope%20to%20hear%20back%20from%20you%20soon.%0D%0A%0D%0AThank%20you.%0D%0A" target="_blank" rel="noopener noreferrer" class="button p-3">Contact Us</a>
                    </div>
                  </div>
                </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-4">
        <h3 id="org-posts" class="mb-4">Posts</h3>
        <div class="cards-grid my-4">
            <% @organisation.posts.each do |post| %>
                <%= link_to organisation_post_path(@organisation, post) do%>
                <div class="card-product">
                  <% if post.photo.attached? %>
                    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(post.photo.key) %>)">
                      <%= post.title %>
                    </div>
                  <% end %>
                </div>
                <% end %>
            <% end %>
          </div>
      </div>
    </div>

    <div class="col-12 col-lg-4 my-4">
      <% if @organisation != current_user&.organisation %>
          <div class=" donation-border container p-5 sticky-top border radius-4">
            <h3>Donate:</h3>
              <%= simple_form_for [@organisation, @donation ] do |f| %>
                <%= f.input :type_of_donation, label: 'Currency', collection: ['€', '$'], placeholder:'Currency'%>
                <%= f.input :quantity, label: 'Amount' %>
                <%= f.input :description %>
                <div class="text-center">
                <%= f.submit "Donate!", class:"button" %>

                <h3 class="mt-5">Or donate with <img src="https://upload.wikimedia.org/wikipedia/commons/b/b5/PayPal.svg" alt="paypal"></h3>

                <div id="donate-button-container">
                <div id="donate-button"></div>
                <script src="https://www.paypalobjects.com/donate/sdk/donate-sdk.js" charset="UTF-8"></script>
                <script>
                  PayPal.Donation.Button({
                  env:'production',
                  hosted_button_id:'UYDYRK86LCZBA',
                  image: {
                  src:'https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif',
                  alt:'Donate with PayPal button',
                  title:'PayPal - The safer, easier way to pay online!',
                  }
                  }).render('#donate-button');
                </script>
                </div>

                <%# <h5 class="mt-5">Every donation counts and goes directly to the project.</h5>
                <h5>To Be Found will change the world</h5> %>

                </div>
              <% end %>
          </div>
        <% end %>
    </div>


  </div>
</div>