config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/thankyou', to: 'pages#thankyou'

  resources :users, only: [:update]

  resources :skills, only: %i[index create edit update]

  resources :organisations, except: %i[destroy] do
    resources :donations, only: %i[create]
    resources :posts, only: %i[index show new create edit update]
    resources :needs, only: %i[index create edit update]
  end

  resources :donations, only: %i[show]

  get '/profile', to: 'profiles#show'

  resources :chatrooms, only: :show

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :organisation

  validates :title, presence: true
  validates :content, presence: true
  has_one_attached :photo
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, except: :new

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @organisation = Organisation.find(params[:organisation_id])
  end

  def new
    @organisation = Organisation.find(params[:organisation_id])
    @post = Post.new
  end

  def create
    @organisation = Organisation.find(params[:organisation_id])
    @post = Post.new(post_params)
    @post.organisation = @organisation
    # @post.user = current_user
    if @post.save
      redirect_to organisation_path(@organisation), notice: "New post created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @organisation = Organisation.find(params[:organisation_id])
    @post = Post.find(params[:id])
    # @post.organisation = @organisation
  end

  def update
    # @organisation = Organisation.find(params[:organisation_id])
    @post = Post.find(params[:id])
    # @post.organisation = @organisation
    @post.update(post_params)

    if @post.save
      redirect_to organisation_post_path(@post.organisation, @post), notice: "Update the post"
    else
      render :new, status: :unprocessable_entity
    end
    # redirect_to organisation_post_path(@organisation, post)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :photo)
  end
end

app/views/posts/_form.html.erb
<%= simple_form_for [organisation, post] do |f| %>

          <%= f.input :photo, as: :file %>
          <%= f.input :title, placeholder: "Post title" %>
          <%= f.input :content, as: :text, placeholder: "write your new shit" %>
          <%= f.submit "Submit", class: 'button' %>
<% end %>

app/views/posts/edit.html.erb
<div class="container p-20 mt-5">
  <h3>Update the post</h3>
  <%= render "form", post: @post, organisation: @organisation %>
</div>

app/views/posts/index.html.erb
<div class="row" >
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1564750576234-75de3cc54053?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGluZGlnZW5vdXMlMjBhbWF6b258ZW58MHwwfDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60)">
      Organisations you can find through our website
    </div>
  </div>

app/views/posts/new.html.erb
<div class="container p-20 mt-5">
        <h3>Create a new post</h3>
        <%= render "form", post: @post, organisation: @organisation %>
</div>

app/views/posts/show.html.erb
<div class="container p-5">
  <div class="row card-post">

    <div class="col-xs-12 col-lg-4">
      <% if @post.photo.attached? %>
        <%= cl_image_tag @post.photo.key %>
      <% end %>
    </div>

    <div class="col-xs-12 col-lg-8">
      <h1><%= @post.title %></h1>
      <p id="date"><%= @post.created_at.strftime("%A, %b %d") %></p>
      <p><%= @post.content %></p>
    </div>

  </div>
</div>

<div class="container mb-5">
    <div class="row">
        <div class="col-xs-12">
            <div  class="text-center">
              <%= link_to 'Back', organisation_path(@organisation, anchor: "org-posts"), class: "button" %>

              <% if @organisation == current_user&.organisation %>
                <%= link_to 'Edit', edit_organisation_post_path(@organisation, @post), class: "button" %>
              <% end %>
            </div>
        </div>
    </div>
</div>